### ISSUE TITLE
VRR doesn't work

### ISSUE THREAD

**Issue by onlyreportingissues** [pop-os/cosmic-randr#20]
Tested it with the AppImage of this tool in COSMIC and GNOME 46 (to compare & check if it's working): https://github.com/Nixola/VRRTest/releases

VRR can be enabled in GNOME 46 with the command: gsettings set org.gnome.mutter experimental-features "['variable-refresh-rate']"

It will be available in the display settings when clicking on Hz after logging in again. In GNOME it started lagging below 48 Hz on my monitor, above it it run like butter. In COSMIC it stutters also when it is above 48 Hz.

**Comment by mmstick** [comment]
Did you mean to file an issue for cosmic-comp?

**Comment by onlyreportingissues** [comment]
Oh, gonna close it here & open it there. 👍
