### ISSUE TITLE
Wrong physical size

### ISSUE THREAD

**Issue by rompetomp** [pop-os/cosmic-randr#29]
I use a 42" LG C2 (4K) as a monitor. When I check cosmic display settings, it shows the monitor as a 72.3" monitor?
![image](https://github.com/user-attachments/assets/d9ecb20a-09dd-4a59-adaf-c26582157750)

After some research I found out that this project exists, and when I run `cosmic-randr list`, the output is this: 
```
  Physical Size: 1600 x 900 mm
```

Which is way too high. The dimensions of the screen itself are  932 x 540mm (with bezels).

Is there a way to let cosmic-randr that this value needs to change, and if so, how?

Thanks in advance

**Comment by Drakulix** [comment]
This value is read from the EDID of the monitor, which is nothing cosmic has control over. THere might be some settings in your TV to change what is reported here. The good news is apart from the reported size and the initial scaling value cosmic chooses, a wrong value has no effect on any functionality.

**Comment by rompetomp** [comment]
> The good news is apart from the reported size and the initial scaling value cosmic chooses, a wrong value has no effect on any functionality.
Are you sure about that? When I run a game through proton, or something like battle.net, the window is really small, and the game runs at a way higher resolution than 4k (I can't check right now, because I'm not at my PC). This is when I enable the new option of Wayland application being run at native resolution.

**Comment by mmstick** [comment]
A pixel is a pixel regardless of the reported physical dimensions of the display.
