### ISSUE TITLE
Incomplete URL in README

### ISSUE THREAD

**Issue by Nioub** [pop-os/cosmic-randr#5]
Hi!

In the [README.md](https://github.com/pop-os/cosmic-randr/blob/master_jammy/README.md) file, the link to "KDL syntax format" should have the protocol added as prefix, like [KDL syntax format](https://kdl.dev/), otherwise it points to an unknown location within this GitHub projet.

I believe you don't need a Pull Request for this 😎.

Best regards,

**Comment by XV-02** [comment]
Fixed by 88c570cf8b88beae1cf4f3e2d412cc64ec49cd7c.
