### ISSUE TITLE
disabling the second display does not work or doesn't cause mouse to stay in the first monitor (with 2 displays)

### ISSUE THREAD

**Issue by sonicrules1234** [pop-os/cosmic-randr#6]
I decided to try out cosmic, and had my valve index plugged into dp-2.  I tried disabling it, but the mouse still goes off the screen to the right instead of stopping at the edge

**Comment by Drakulix** [comment]
Just to be sure, is the Index initialized as a second output? Does it display stuff (before and after changing it's state in cosmic-randr)?

Because we explicitly don't take headsets into account.

**Comment by sonicrules1234** [comment]
I also just tried with my steam deck and an external monitor.  Steam deck screen is showing up as eDP-1 in cosmic-randr list, but running `cosmic-randr disable eDP-1` does not disable it.  I can move the mouse from the external display to the steam deck screen.

**Comment by Pharmasolin** [comment]
Laptop with a connected external monitor (display port) and TV (HDMI). I can't disable any monitor (and built in display) it just focuses on monitor with 0 index (in a settings app).

Package: cosmic-session
Version: 0.1.0~1709999281~22.04~3fc8c8d
Package: cosmic-randr
Version: 0.1.0~1705615670~22.04~88c570c
Package: cosmic-settings
Version: 0.1.0~1710285950~22.04~d6b2823

**Comment by shawn111** [comment]
```
$ cosmic-randr  disable  eDP-1
Error: "configuration failed"
```

wlr-randr works for me, now I can disable my monitor.



wlr-randr --output  eDP-1 --off

**Comment by shawn111** [comment]
cosmic-desktop-0.1.0~git20240514.00.none-1.fc40.x86_64
cosmic-randr-0.1.0~git20240514.22.8ad117e-1.fc40.x86_64

this issue is fixed
